name: depup
on:
  schedule:
    - cron:  '14 14 * * *' # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update reviewdog to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update reviewdog to ${{ steps.depup.outputs.latest }}"
          body: |
            Update reviewdog to [v${{ steps.depup.outputs.latest }}](https://github.com/reviewdog/reviewdog/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/reviewdog/reviewdog/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/reviewdog
          base: master
          labels: "bump:minor"

  tmpl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: TMPL_VERSION
          repo: haya14busa/tmpl

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update tmpl to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update tmpl to ${{ steps.depup.outputs.latest }}"
          body: |
            Update tmpl to [v${{ steps.depup.outputs.latest }}](https://github.com/haya14busa/tmpl/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/haya14busa/tmpl/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/tmpl
          base: master
          labels: "bump:patch"

  offset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: OFFSET_VERSION
          repo: haya14busa/offset

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update offset to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update offset to ${{ steps.depup.outputs.latest }}"
          body: |
            Update offset to [v${{ steps.depup.outputs.latest }}](https://github.com/haya14busa/offset/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/haya14busa/offset/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/offset
          base: master
          labels: "bump:patch"

  ghglob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: GHGLOB_VERSION
          repo: haya14busa/ghglob

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update ghglob to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ghglob to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ghglob to [v${{ steps.depup.outputs.latest }}](https://github.com/haya14busa/ghglob/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/haya14busa/ghglob/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/ghglob
          base: master
          labels: "bump:patch"
